repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=1024"]
        # exclude: |
        #   (?x)^(
        #     lime/src/build/esbuild_v0.19.2.wasm
        #   )$
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: pretty-format-json
        args: ["--autofix", "--no-ensure-ascii", "--no-sort-keys"]
      - id: trailing-whitespace
  - repo: https://github.com/crate-ci/typos
    rev: v1.22.9
    hooks:
      - id: typos
        verbose: true
        args: []
        exclude: |
          (?x)^(
            node_modules/.*|
            test/coverage/.*|
            test/html_cov/.*|
          )$
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.2.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: []
  - repo: local
    hooks:
      #     - id: kebab-case-files-only
      #       name: kebab-case files only
      #       entry: filenames must be kebab-case only
      #       language: fail
      #       files: '(?!\_test\.[jt]sx?$)[^a-z0-9.\/\[\]@-]'
      #       exclude: |
      #         (?x)^(
      #           .github/ISSUE_TEMPLATE/bug_report.md|
      #           .github/ISSUE_TEMPLATE/feature_request.md|
      #           .github/PULL_REQUEST_TEMPLATE.md|
      #           .github/FUNDING.yml|
      #           pkg/main/routes/dash/\(_islands\)/chart.tsx|
      #           pkg/main/routes/_404.tsx|
      #           pkg/main/routes/_500.tsx|
      #           pkg/main/routes/_layout.tsx|
      #           pkg/main/routes/_app.tsx|
      #           test/cov_profile.lcov|
      #           test/html_cov/.*|
      #           CODE_OF_CONDUCT.md|
      #           LICENSE|
      #           CODEOWNERS|
      #           CONTRIBUTING.md|
      #           README.md|
      #           SECURITY.md|
      #           Makefile|
      #           Dockerfile|
      #         )$
      - id: local-tasks
        name: local pre-commit tasks
        description: Runs local pre-commit tasks.
        entry: bash -c 'deno task ok; git add -u' --
        types_or: [javascript, jsx, ts, tsx, json, markdown]
        # always_run: true
        pass_filenames: false
        language: system
